use_frameworks!
source 'https://github.com/CocoaPods/specs.git'
source 'https://github.com/Andriel-lore/cocoapods.git'

platform :ios, '10.0'

target 'animal_cage_Example' do
  pod 'animal_cage', :path => '../'

  target 'animal_cage_Tests' do
    inherit! :search_paths

    
  end
end
